name: NodeJS with Grunt

on:
  push:
    branches: ['test']
  pull_request:
    branches: ['test']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
